"""add_tabela_maquinas

Revision ID: 371777fd500e
Revises: 89bb0242dff0
Create Date: 2026-10-05 16:02:50.810128
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '371777fd500e'
down_revision: Union[str, Sequence[str], None] = '89bb0242dff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maquinas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario', sa.String(), nullable=True),
    sa.Column('nome_maquina', sa.String(), nullable=False),
    sa.Column('usuario_ad', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('sistema_operacional', sa.String(), nullable=True),
    sa.Column('office', sa.String(), nullable=True),
    sa.Column('setor', sa.String(), nullable=True),
    sa.Column('antivirus', sa.String(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maquinas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maquinas_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maquinas_ip'), ['ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_maquinas_nome_maquina'), ['nome_maquina'], unique=False)
        batch_op.create_index(batch_op.f('ix_maquinas_setor'), ['setor'], unique=False)
        batch_op.create_index(batch_op.f('ix_maquinas_usuario'), ['usuario'], unique=False)
        batch_op.create_index(batch_op.f('ix_maquinas_usuario_ad'), ['usuario_ad'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maquinas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maquinas_usuario_ad'))
        batch_op.drop_index(batch_op.f('ix_maquinas_usuario'))
        batch_op.drop_index(batch_op.f('ix_maquinas_setor'))
        batch_op.drop_index(batch_op.f('ix_maquinas_nome_maquina'))
        batch_op.drop_index(batch_op.f('ix_maquinas_ip'))
        batch_op.drop_index(batch_op.f('ix_maquinas_id'))

    op.drop_table('maquinas')
    # ### end Alembic commands ###
