"""add_status_lista_compras

Revision ID: 89bb0242dff0
Revises: aaef859c49de
Create Date: 2026-09-04 14:11:10.205843
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '89bb0242dff0'
down_revision: Union[str, Sequence[str], None] = 'aaef859c49de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lista_compras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), server_default='pendente', nullable=False))
        
    op.execute("UPDATE lista_compras SET status = 'entregue' WHERE comprado = 1")
    op.execute("UPDATE lista_compras SET status = 'pendente' WHERE comprado = 0")
    
    with op.batch_alter_table('lista_compras', schema=None) as batch_op:
        batch_op.drop_column('comprado')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lista_compras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comprado', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
