"""add_entregue_para_and_observacao

Revision ID: aaef859c49de
Revises: d313605dad1a
Create Date: 2026-09-03 07:25:53.787384
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aaef859c49de'
down_revision: Union[str, Sequence[str], None] = 'd313605dad1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entregue_para', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('observacao', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacoes', schema=None) as batch_op:
        batch_op.drop_column('observacao')
        batch_op.drop_column('entregue_para')

    # ### end Alembic commands ###
